config/routes.rb
Rails.application.routes.draw do
  resources :results
  root 'results#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
    def self.search(search)
        GoogleBooks.search(search)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = Result.search(params[:search])
    @books = GoogleBooks.search(params[:search])
    @first_book = @books.first
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results/index.html.erb
<h1>Google Books Search</h1>

<%= form_tag(results_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Search") %>
<% end %>
<br>
<p><%= @test %>

<%= form_for @results do |f| %>
    <% @books %>
    <br>
    <%= f.label :title %><br>
    <br>
    <%= f.label :author %><br>
    <br>
    <%= f.label :company %><br>
<% end %>